const SET_CURRENT_ACTIVE_LOCATIONS = 'TAKE_LOCATIONS'
const CHANGE_DELIVERY_POINT = 'CHANGE_DELIVERY_POINT'

const SET_ORDERS = 'SET_ORDERS'
const FETCH_ORDERS = 'FETCH_ORDERS'

export { SET_CURRENT_ACTIVE_LOCATIONS, CHANGE_DELIVERY_POINT, SET_ORDERS, FETCH_ORDERS }